@startuml

!define LightYellow #FFF9D6
!define LightGreen #D2F2C2
!define LightBlue #D6E3FF

skinparam packageStyle rect
skinparam packageBackgroundColor LightYellow
skinparam packageTitleBackgroundColor LightGreen
skinparam defaultFontName Arial
skinparam defaultFontSize 12

actor User as user
actor "Tài xế" as driver

user --> [Đăng ký và đăng nhập]
user --> [Quản lý tài khoản]
user --> [Tìm kiếm và đặt xe]
user --> [Thanh toán và đánh giá]

driver --> [Đăng ký và đăng nhập]
driver --> [Quản lý tài khoản]
driver --> [Nhận và quản lý đơn hàng]
driver --> [Chuyến đi và nhận thanh toán]
driver --> [Đánh giá]

@enduml